### ISSUE TITLE
Not able to install without renaming plugin folder

### ISSUE THREAD

**Issue by p-bo** [JulioAugustoS/glpiorderservice#4]
Hi,
Extracted from 
glpi-orderservice-0.1.3.tar.bz2 into plugins directory. Plugin didn't showed on plugins management page in GLPI. Had to rename directory glpiorderservice to orderservice only. After then, plugin appeared on plugins management page and was able to install.

**Comment by JulioAugustoS** [comment]
Forgive me for failing my friend, I'll be correcting this question.
