### ISSUE TITLE
Try to find how it's works !

### ISSUE THREAD

**Issue by jfg** [JulioAugustoS/glpiorderservice#9]
Hi,

i'm earching a manual for uses your plugin correctly !

My installation is OK but i can't find where i can generate my order.
I don't find the file for switch language in French.

**Comment by JulioAugustoS** [comment]
Hello friend, I apologize for not having put in the manual how to add the buttons that pass the information of the ticket to the plugin, look again in the manual of the plugin that is all explained now, any doubt I am the arrangement.

**Comment by jfg** [comment]
Thanks for the update Julio !

And for change language in French ?
Do you have a parameter or file to translate ?

**Comment by JulioAugustoS** [comment]
Have a friend, the language issue I have not done part of the translation, I'm working on it.

**Comment by jfg** [comment]
Good ;)
Thanks for your work !

**Comment by JulioAugustoS** [comment]
Thanks, my friend, I'm working on the translation for other languages, so when I'm finished I'll be launching in version 0.1.5, what language would you like to use?

**Comment by jfg** [comment]
French for me.

I think you should create a translation file that contains all the texts. So, we could easily translate the plugin.

**Comment by JulioAugustoS** [comment]
Ok, I'm just doing this, the intention is that people can contribute in translation and in new features, any help will always be welcome.

**Comment by jfg** [comment]
Ok Good.
I can Help for translation in French and English.
And for try your Beta Version.
And contribute for new features.

**Comment by JulioAugustoS** [comment]
Ok, my friend, I'm happy for this and thank you very much.
